name: Deployment Exercise - multiple jobs solution
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Get code
      uses: actions/checkout
    - name: Install dependencies
      run: npm ci
    - name: Lint
      run: npm run lint

  test:
    runs-on: ubuntu-latest
    steps:
    - name: Get code
      uses: actions/checkout
    - name: Install dependencies
      run: npm ci
    - name: Test code
      run: npm run test

  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Get code
      uses: actions/checkout
    - name: Install dependencies
      run: npm ci
    - name: Deploy App
      run: echo "Deploying..."
